<template>
  <Card
    class="from-background via-background to-muted/30 overflow-hidden bg-linear-to-br"
    data-testid="ai-insights"
  >
    <!-- AI Summary Section -->
    <div class="space-y-4 p-4">
      <div class="flex items-center gap-3">
        <div
          class="flex size-10 items-center justify-center rounded-full bg-linear-to-br from-blue-500 to-cyan-500"
          data-testid="ai-summary-icon"
        >
          <Sparkles class="size-5 text-white" />
        </div>
        <div>
          <h3 class="text-foreground font-semibold">AI Summary</h3>
          <p class="text-muted-foreground text-xs">Generated by Claude</p>
        </div>
      </div>

      <div
        class="text-sm/relaxed"
        :class="
          hasValidSummary
            ? 'text-foreground/90'
            : 'text-muted-foreground italic'
        "
      >
        <p>{{ summary }}</p>
      </div>
    </div>

    <!-- Divider -->
    <div class="flex items-center gap-4 px-4">
      <div class="bg-border h-px flex-1" />
      <span class="text-muted-foreground text-xs font-medium">
        Other perspectives
      </span>
      <div class="bg-border h-px flex-1" />
    </div>

    <!-- LLM Hotlinks Section -->
    <div class="p-4 pt-4">
      <div
        ref="containerRef"
        class="relative flex h-40 w-full items-center justify-center"
      >
        <!-- Left side LLMs -->
        <div
          class="absolute left-2 flex flex-col justify-center gap-6 md:left-8"
        >
          <a
            ref="chatgptRef"
            aria-label="Open ChatGPT to analyze this candidate's profile"
            class="group bg-background relative z-10 flex size-12 cursor-pointer items-center justify-center rounded-full border-2 shadow-lg transition-all hover:scale-110 hover:shadow-xl"
            data-testid="llm-button"
            :href="chatgptUrl"
            rel="noopener noreferrer"
            :style="{ borderColor: '#10A37F' }"
            target="_blank"
          >
            <ChatGPTIcon
              class="size-5"
              style="color: #10a37f"
            />
            <span
              class="text-muted-foreground absolute -bottom-5 left-1/2 -translate-x-1/2 text-xs font-medium whitespace-nowrap opacity-0 transition-opacity group-hover:opacity-100"
            >
              ChatGPT
            </span>
          </a>
          <a
            ref="claudeRef"
            aria-label="Open Claude to analyze this candidate's profile"
            class="group bg-background relative z-10 flex size-12 cursor-pointer items-center justify-center rounded-full border-2 shadow-lg transition-all hover:scale-110 hover:shadow-xl"
            data-testid="llm-button"
            :href="claudeUrl"
            rel="noopener noreferrer"
            :style="{ borderColor: '#D97757' }"
            target="_blank"
          >
            <ClaudeIcon
              class="size-5"
              style="color: #d97757"
            />
            <span
              class="text-muted-foreground absolute -bottom-5 left-1/2 -translate-x-1/2 text-xs font-medium whitespace-nowrap opacity-0 transition-opacity group-hover:opacity-100"
            >
              Claude
            </span>
          </a>
        </div>

        <!-- Center dot -->
        <div
          ref="centerRef"
          class="ring-background z-10 flex size-10 items-center justify-center rounded-full bg-linear-to-br from-blue-500 to-cyan-500 shadow-lg ring-2"
        >
          <span class="text-sm font-bold text-white">AJ</span>
        </div>

        <!-- Right side LLMs -->
        <div
          class="absolute right-2 flex flex-col justify-center gap-6 md:right-8"
        >
          <a
            ref="geminiRef"
            aria-label="Open Gemini to analyze this candidate's profile"
            class="group bg-background relative z-10 flex size-12 cursor-pointer items-center justify-center rounded-full border-2 shadow-lg transition-all hover:scale-110 hover:shadow-xl"
            data-testid="llm-button"
            :href="geminiUrl"
            rel="noopener noreferrer"
            :style="{ borderColor: '#4285F4' }"
            target="_blank"
          >
            <GeminiIcon
              class="size-5"
              style="color: #4285f4"
            />
            <span
              class="text-muted-foreground absolute -bottom-5 left-1/2 -translate-x-1/2 text-xs font-medium whitespace-nowrap opacity-0 transition-opacity group-hover:opacity-100"
            >
              Gemini
            </span>
          </a>
          <a
            ref="perplexityRef"
            aria-label="Open Perplexity to analyze this candidate's profile"
            class="group bg-background relative z-10 flex size-12 cursor-pointer items-center justify-center rounded-full border-2 shadow-lg transition-all hover:scale-110 hover:shadow-xl"
            data-testid="llm-button"
            :href="perplexityUrl"
            rel="noopener noreferrer"
            :style="{ borderColor: '#00C9FF' }"
            target="_blank"
          >
            <PerplexityIcon
              class="size-5"
              style="color: #00c9ff"
            />
            <span
              class="text-muted-foreground absolute -bottom-5 left-1/2 -translate-x-1/2 text-xs font-medium whitespace-nowrap opacity-0 transition-opacity group-hover:opacity-100"
            >
              Perplexity
            </span>
          </a>
        </div>

        <!-- Animated Beams -->
        <AnimatedBeam
          v-if="isReady && containerRef && centerRef && chatgptRef"
          :container-ref="containerRef"
          :curvature="60"
          :duration="4"
          :end-ref="chatgptRef"
          gradient-start-color="#10A37F"
          gradient-stop-color="#1A7F64"
          path-color="gray"
          :path-opacity="0.15"
          :start-ref="centerRef"
        />
        <AnimatedBeam
          v-if="isReady && containerRef && centerRef && claudeRef"
          :container-ref="containerRef"
          :curvature="-60"
          :duration="4.5"
          :end-ref="claudeRef"
          gradient-start-color="#D97757"
          gradient-stop-color="#C4694B"
          path-color="gray"
          :path-opacity="0.15"
          :start-ref="centerRef"
        />
        <AnimatedBeam
          v-if="isReady && containerRef && centerRef && geminiRef"
          :container-ref="containerRef"
          :curvature="-60"
          :duration="5"
          :end-ref="geminiRef"
          gradient-start-color="#4285F4"
          gradient-stop-color="#1967D2"
          path-color="gray"
          :path-opacity="0.15"
          reverse
          :start-ref="centerRef"
        />
        <AnimatedBeam
          v-if="isReady && containerRef && centerRef && perplexityRef"
          :container-ref="containerRef"
          :curvature="60"
          :duration="4.2"
          :end-ref="perplexityRef"
          gradient-start-color="#00C9FF"
          gradient-stop-color="#0099CC"
          path-color="gray"
          :path-opacity="0.15"
          reverse
          :start-ref="centerRef"
        />
      </div>

      <div class="mt-2 flex justify-center">
        <button
          aria-label="Copy prompt to clipboard"
          class="text-muted-foreground hover:text-foreground flex cursor-pointer items-center gap-2 text-xs transition-colors"
          data-testid="copy-button"
          type="button"
          @click="copyPrompt"
        >
          <component
            :is="copied ? Check : Copy"
            class="size-3"
          />
          {{ copied ? "Prompt copied!" : "Copy prompt to clipboard" }}
        </button>
      </div>
    </div>
  </Card>
</template>

<script setup lang="ts">
import { useClipboard } from "@vueuse/core";
import { Check, Copy, Sparkles } from "lucide-vue-next";
import { computed, nextTick, onMounted, ref } from "vue";

import {
  ChatGPTIcon,
  ClaudeIcon,
  GeminiIcon,
  PerplexityIcon,
} from "@/components/icons";
import { AnimatedBeam, Card } from "@/components/ui";
import aiSummaryData from "@/data/ai-summary.json";

interface Props {
  prompt: string;
}

const props = defineProps<Props>();

const FALLBACK_SUMMARY = "Summary unavailable. Please try again later.";

const summary: string = aiSummaryData.summary || FALLBACK_SUMMARY;
const hasValidSummary: boolean = summary !== FALLBACK_SUMMARY;

const containerRef = ref<HTMLElement | null>(null);
const centerRef = ref<HTMLElement | null>(null);
const chatgptRef = ref<HTMLElement | null>(null);
const claudeRef = ref<HTMLElement | null>(null);
const geminiRef = ref<HTMLElement | null>(null);
const perplexityRef = ref<HTMLElement | null>(null);
const isReady = ref<boolean>(false);

const { copy, copied } = useClipboard({ copiedDuring: 2000 });

const encodedPrompt = computed<string>(() => encodeURIComponent(props.prompt));

const chatgptUrl = computed<string>(
  () => `https://chat.openai.com/?q=${encodedPrompt.value}`
);

const claudeUrl = computed<string>(
  () => `https://claude.ai/new?q=${encodedPrompt.value}`
);

const geminiUrl = computed<string>(
  () => `https://www.google.com/search?q=${encodedPrompt.value}&udm=50`
);

const perplexityUrl = computed<string>(
  () => `https://www.perplexity.ai/?q=${encodedPrompt.value}`
);

function copyPrompt(): void {
  copy(props.prompt);
}

onMounted(async (): Promise<void> => {
  await nextTick();

  setTimeout((): void => {
    isReady.value = true;
  }, 200);
});
</script>
