<template>
  <Card
    class="from-background via-background to-muted/30 overflow-hidden bg-linear-to-br"
  >
    <div class="space-y-4 p-6">
      <div class="flex items-center gap-3">
        <div
          class="flex h-10 w-10 items-center justify-center rounded-full bg-linear-to-br from-blue-500 to-cyan-500"
          data-testid="ai-summary-icon"
        >
          <Sparkles class="h-5 w-5 text-white" />
        </div>
        <div>
          <h3 class="text-foreground font-semibold">AI Summary</h3>
          <p class="text-muted-foreground text-xs">Generated by Claude</p>
        </div>
      </div>

      <div
        class="text-sm leading-relaxed"
        :class="
          hasValidSummary
            ? 'text-foreground/90'
            : 'text-muted-foreground italic'
        "
      >
        <p>{{ summary }}</p>
      </div>
    </div>
  </Card>
</template>

<script setup lang="ts">
import { Sparkles } from "lucide-vue-next";
import { computed } from "vue";

import { Card } from "@/components/ui";
import aiSummaryData from "@/data/ai-summary.json";

interface AiSummaryData {
  generatedAt?: string;
  summary?: string;
}

const FALLBACK_SUMMARY = "Summary unavailable. Please try again later.";

const summary = computed<string>(() => {
  const data = aiSummaryData as AiSummaryData;

  if (!data || typeof data.summary !== "string" || data.summary.trim() === "") {
    return FALLBACK_SUMMARY;
  }

  return data.summary;
});

const hasValidSummary = computed<boolean>(
  () => summary.value !== FALLBACK_SUMMARY
);
</script>
