import { mount } from "@vue/test-utils";

import type { RenderOptions } from "@/test/utils";

import AiSummary from "./AiSummary.vue";

const render = (options: RenderOptions<typeof AiSummary> = {}) => {
  const wrapper = mount(AiSummary, {
    global: {
      ...options.global,
    },
    props: {
      ...options.props,
    },
  });

  return { wrapper };
};

describe("AiSummary", () => {
  describe("rendering", () => {
    it("renders the component", () => {
      const { wrapper } = render();
      expect(wrapper.exists()).toBe(true);
    });

    it("renders the title", () => {
      const { wrapper } = render();
      expect(wrapper.text()).toContain("AI Summary");
    });

    it("renders the subtitle", () => {
      const { wrapper } = render();
      expect(wrapper.text()).toContain("Generated by Claude");
    });

    it("renders summary content from the JSON data", () => {
      const { wrapper } = render();
      expect(wrapper.text()).toContain("Andres Janes");
    });
  });

  describe("card wrapper", () => {
    it("wraps content in a Card component", () => {
      const { wrapper } = render();
      expect(wrapper.findByTestId("card").exists()).toBe(true);
    });
  });

  describe("icon", () => {
    it("renders Sparkles icon container", () => {
      const { wrapper } = render();
      expect(wrapper.findByTestId("ai-summary-icon").exists()).toBe(true);
    });
  });
});
