<script setup lang="ts">
import { Sparkles } from 'lucide-vue-next'

import { Card } from '@/components/ui'
import aiSummaryData from '@/data/ai-summary.json'

const summary = aiSummaryData.summary
</script>

<template>
    <Card class="overflow-hidden bg-linear-to-br from-background via-background to-muted/30">
        <div class="p-6 space-y-4">
            <div class="flex items-center gap-3">
                <div class="flex items-center justify-center w-10 h-10 rounded-full bg-linear-to-br from-blue-500 to-cyan-500">
                    <Sparkles class="w-5 h-5 text-white" />
                </div>
                <div>
                    <h3 class="font-semibold text-foreground">AI Summary</h3>
                    <p class="text-xs text-muted-foreground">Generated by Claude</p>
                </div>
            </div>

            <div class="text-sm leading-relaxed text-foreground/90">
                <p>{{ summary }}</p>
            </div>
        </div>
    </Card>
</template>
